### ISSUE TITLE
PersonalQuestion and EconomicQuestion Model Representation 

### ISSUE THREAD

**Issue by bhylak** [wpi-poverty-stoplight/ps-advisor-app#23]
Our model should be changed so PersonalQuestion and EconomicQuestion share the same type. Whether this is an interface or a parent class doesn't really matter, it's just too hard to manage lists of questions. All of these questions are asked during the background portion of the survey.

We do need to be able to distinguish between Personal and Economic though (like if we want to autofill personal data, for example). Maybe a flag of some sort?

**Comment by krconv** [comment]
We could even merge the two into a base class BackgroundQuestion, while still keeping them in different lists in the survey. Actual change won't be too bad, but it will require some reworking of the survey functionality in that activity along with the IR->Model conversion
