### ISSUE TITLE
Fix depricated code in LocationQuestionFrag

### ISSUE THREAD

**Issue by alextac98** [wpi-poverty-stoplight/ps-advisor-app#354]
Fix depricated code in QuestionFragment
 
GooglePlayServices.getErrorDialog is depricated

`public static class LocationQuestionFrag extends QuestionFragment {

        private Button mLocationPicker;
        private int PLACE_PICKER_REQUEST = 1;

        @Override
        public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
            View v = inflater.inflate(R.layout.item_questionlocation, container, false);

            mLocationPicker = v.findViewById(R.id.btn_set_location);

            mLocationPicker.setOnClickListener(view -> {
                if (Utilities.isGooglePlayServicesAvailable(getActivity())) {
                    PlacePicker.IntentBuilder builder = new PlacePicker.IntentBuilder();
                    Intent intent;
                    try {
                        intent = builder.build(getActivity());
                        startActivityForResult(intent, PLACE_PICKER_REQUEST);
                    } catch (GooglePlayServicesRepairableException e) {

                        //Depricated code below
                        GooglePlayServicesUtil.getErrorDialog(e.getConnectionStatusCode(), getActivity(), 0);

                    } catch (GooglePlayServicesNotAvailableException e) {
                        Toast.makeText(getActivity(), "Google Play Services is not available.",
                                Toast.LENGTH_LONG)
                                .show();
                    }
                }
            });

            return v;
        }`

**Comment by bhylak** [comment]
if you find an issue this minor, feel free to fix it yourself.
