### ISSUE TITLE
Data erased on failed login

### ISSUE THREAD

**Issue by bhylak** [wpi-poverty-stoplight/ps-advisor-app#467]
So this was seen during Test2, User 1 the other day.

App crashed, so the user went to launch it again. Then it crashed again on the dashboard activity. 

Anyway, they went to login again and it didn't have their credentials cached. Or maybe it tried to load briefly and failed. All of their data was erased.

Couple of suggestions here:

1. We should try to sync on log out. If there's no internet connection, then we should let them know everything will be lost. (Related to #204) This wouldn't have fixed this particularly issue though, because the user never logged out.

2. We should not erase when the state is unauthenticated. If the same user authenticates again, can't we just load their data back? 

```
private AuthenticationStatus updateStatus(AuthenticationStatus newStatus) {
        if (newStatus == mStatus.getValue())
            return newStatus;

        mStatus.postValue(newStatus);

        switch (newStatus) {
            case AUTHENTICATED:
                SyncJob.startPeriodic();
                break;
            case UNAUTHENTICATED:
                SyncJob.stopPeriodic();
                CleanJob.clean();
                break;
        }
        return newStatus;
}
```

# Update (April 10, 2018):

Doing some work to figure out why we are losing our auth state.

## Notes
* Authentication status can change in interceptor because login is attempted (hence the null pointer…)
* Triggering authentication status also triggers a sync, or a clean job if unauthenticated.
* Initially authenticated, then goes to unauthenticated

## Updates to Status (Logged)
1. Login task -> authenticates successfully
2. Gets an unauthorized message from the chain
3. Attempts to relogin
4. Then status -> pending
5. then status -> false (169)

Something must be wrong with the refresh key.

When commenting out the login call in the interceptor, we don't error, but we can also see that our access token is invalid:

`04-10 15:31:36.175 14383-14462/org.fundacionparaguaya.adviserplatform E/SnapshotRepository: pullSnapshots: Could not pull snapshots for family 10! {"error":"invalid_token","error_description":"Invalid access token: 780b6030-41ed-4538-8f22-3747a3a30376"}`

**Comment by krconv** [comment]
Still an issue
